version: '3'

services:
  # mysql:
  #   container_name: steam_db_pgsql
  #   image: mysql:8
  #   volumes:
  #     - ./db/MySQL:/var/lib/mysql
  #   ports:
  #     - 3576:3306
  #   restart: always
  #   environment:
      # MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_DATABASE: ${DB_DATABASE}

  pgsql:
    container_name: steam_db_pgsql
    image: postgres:12-alpine
    volumes: 
      - ./dbPGSQL/PgSQL:/var/lib/postgresql/data
    ports:
      - '5434:5432'
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
